@startuml
start
:Пользователь выбирает товар в системе;
if (Пользователь зарегистрирован в системе) is(Да) then
:Данные пользователя проверяются в сервисе авторизации;
else(Нет)
  :Пользователь заполняет данные для регистрации;
  note right
Методом post/user создается пользователь
end note
endif
if (Данные валидны) is(Да) then
:Данные записываются/хранятся в БД сервиса авторизации;
:Сервис авторизации отправляет 200ОК;
else(Нет)
  stop
endif
:Пользователь оформляет заказ;
note right
Методом get получаем актуальную 
информацию о товарах c с сервиса товаров;
end note
if (Товар есть в наличии в магазине?) is(Да) then
:Пользователь переходит на страницу оформления заказа;
note left
В БД сервиса товаров меняется количество товара, 
т.к товар в резерве
end note
else(Нет)
  :Пользователю предлагается доставка со склада;
  note right
Методом get получаем актуальную 
информацию о товарах c с сервиса складов;
end note
  :Пользователь выбирает способ доставки;
    note right
Данные записываются в БД сервиса доставки
end note
endif
  :Пользователь переходит на страницу оплаты;
note right
Сервис обработки заказов через броккер 
обращается в систему обработки платажей
end note
if (Транзакция прошла?) is(Да) then
:Пользователю отображается модальное окно \nоб успешном оформлении заказа;
note left
Данные записываются в БД сервиса обработки заказов
end note
else(Нет)
  stop
endif
:Пользователь следит за статусом заказа;
note left
Данные приходят из сервиса уведомлений
end note
:Пользователь получает заказ;
note left
В БД сервиса заказов меняется статус на "Доставлено"
end note
stop

@enduml