@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())
LAYOUT_WITH_LEGEND()
!$COLOR_B_4 = "#542788"
UpdateElementStyle("external_system", $bgColor=$COLOR_B_4, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_B_2, $legendText="External system")

Person(customer, "Покупатель", "Просматривает каталог товаров, совершает различные операции в системах")
Person(administrator, "Оператор", "Проверяет работоспособность систем, поддерживает функциональность")
System_Boundary(s1, "Управление маркетинговыми процессами") {
    Container(web, "Веб-приложение", "Java", "Предоставляет пользователям доступ к сайту строительной компании" )
    Container(Product_sales_system, "Сервис поиска товаров", "JavaScript, Angular", "Хранит актуальное колиство товаров")
    Container(Order_system, "Сервис обработки заказов", "Java", "Оформление заказов, управление статусами.")
    Container(Customer_system, "Сервис авторизции", "Java", "Настройка прав доступа")
    Container(Storage_system, "Сервис складов", "Java", "Проверка товаров на наличие.")
    Container(backend_api, "Web API Geteway", "Java, Docker Container", "Установка взаимодействия по API")
    ContainerDb(database1, "Database Customer", "Postgre SQL", "База данных для хранения информации")
    ContainerDb(database2, "Database Storage", "Postgre SQL", "База данных для хранения информации")
    ContainerDb(database3, "Database Order", "Postgre SQL", "База данных для хранения информации")
    ContainerDb(database4, "Database Delivery", "Postgre SQL", "База данных для хранения информации")
    ContainerDb(database5, "Database Product", "Postgre SQL", "База данных для хранения информации")
    ContainerQueue(queue, "Брокер", "Rabbit", "Очередь заказов")
    Container(sms, "Сервис уведомлений", "Java", "Отправляет пользователю уведомления")
    Container(Delivery_system, "Сервис доставки", "JavaScript, Angular", "Управление и отслеживание процесса доставки.")
    ContainerDb(cache, "Cache Database", "Memcached","БД для кеширования")
    ContainerDb(cache1, "Cache Database", "Memcached","БД для кеширования")
}
System(s2, "Система обработки платажей", "Совершение покупок, управление транзакциями.")
System_Ext(shardsystem, "Redis cluster")

    Container_Ext(Shard, "Shard #1"){
        ContainerDb(master1,"Redis Master")
        ContainerDb(slave, "Redis Replica ")
        ContainerDb(slave2, "Redis Replica ")
        ContainerDb(slave3, "Redis Replica ") 
    }


Rel(customer, web, "Просматривает каталог и делает заказ")
Rel(administrator, web, "Вносит правки")
Rel(backend_api, Customer_system, "Отправляет запрос на регистрацию или авторизацию")
Rel(Customer_system,database1, "Записывет данные по клиенту")
Rel(web,backend_api,"REST API","JSON/HTTPS")
Rel(backend_api, Product_sales_system, "Делает запрос на поиск товаров", "REST API")
Rel(backend_api, Storage_system, "Проверяет наличие товара на складе","REST API")
Rel(backend_api, Order_system, "Оформляет заказ для определенного пользователя и возвращает ответ")
Rel(backend_api,sms, "Запрос на получение уведомлений")
Rel(Storage_system,database2, "Идет за данными в основную БД")
Rel(Order_system,database3, "Хранит данные о клиентах и их заказах")
Rel(Order_system,queue, "Совершение транзакций")
Rel(queue,s2, "Оплата товара")
Rel(Storage_system,cache,"Проверяет есть ли данные по запросу в кеше")
Rel_L(cache,Storage_system,"Данные не найдены", $tags="backup")
Rel(backend_api, Delivery_system, "Отслеживает доставку")
Rel(Delivery_system, database4, "хранит данные о доставке")
Rel(Product_sales_system, database5, "хранит данные о товарах")
Rel(Product_sales_system,cache1,"Проверяет есть ли данные по запросу в кеше")
Rel(cache1,Product_sales_system,"Данные не найдены", $tags="backup")
Rel_D(cache,Shard,"")
Rel_D(cache1, shardsystem,"")
Rel(master1, slave,"")
Rel(master1,slave2,"")
Rel(master1,slave3,"")

@enduml
