@startuml
title Relational database 
skinparam linetype ortho

entity "Users" as e01 {
  idUser : integer **"PK"**
  --
  name : varchar
  surmame : text
  number : integer
  e-mail : text
  numberDiscountCard : integer **"FK"**
}

entity "Products" as e02 {
  idProduct : integer **"PK"**
  --
  article : integer
  name: text
  quantityShops : integer
  countryOfOrigin : text
}

entity "Orders" as e03 {
  idOrder : integer **"PK"**
  --
  productName: integer 
  productAmount : integer
  orderDate : datetime
  employee : text **"FK"**
  idUser : integer **"FK"**
  deliveryMethod : text
  orderАmount : integer
}

entity "DiscountCards" as e04 {
  numberDiscountCard : integer 
  discountAmount : integer 
}

entity "Employees" as e05 {
  idEmployees : integer **"PK"**
  --
  surname : text 
  name : text
  number : integer 
  passportDetails : text
  jobTitle : text
}

entity "Payment" as e06 {
  idPayment : integer **"PK"**
  --
  orderАmount : text **"FK"**
  paymentMethod : text
  paid : boolean
}

entity "Shops" as e07 {
  storeCode: integer **"PK"**
  --
  storeAddress : text
  quantityStocks : integer
  quantityShops : integer
  shopAddress : text
}

entity "Deliveries" as e08 {
  deliveryCode : integer **"PK"**
  --
  carrierName : text 
  article : integer **"FK"**
  
}



e01 ||--o{ e03
e01 ||--|| e04
e07 }|--o{ e02
e07 }o--|| e08
e05 ||--|| e07
e03 }o--|| e06
e03 ||--o{ e02
@enduml
