@startuml

skinparam linetype ortho

entity "Users" as e01 {
    userId : objectId **"PK"**
  --
  name : string
  surmame : string
  number : long
  e-mail : string
  numberDiscountCard : object 
}
object "numberDiscountCard" as e02 {
    
    number : long
}

entity "Orders" as e03 {
  orderId : objectId **"PK"**
  --
  product: array 
  orderDate : timestamp
  payment : array  
}
object "Product" as e04{
  article : long
  name: string
  quantity : long
  countryOfOrigin : string
  userId : objectId
}
object "Payment" as e05{
  paymentMethod : string
  paid : boolean
  deliveryMethod : string
}
e01 ||--|| e02
e03 }|--o{ e04
e03 }|--o{ e05
e01 ||--o{ e03
@enduml