
= Микросервисная архитектура для компании по продаже строительных материалов

=== Автор: [Ксения]
=== Дата: [28.01.2025]

== Введение
В данном документе описывается подход к разбиению монолитного приложения компании на микросервисы.  

== Подход к разбиению монолита
Для распиливания монолита будет использоваться подход, основанный на доменных областях бизнеса (Domain-Driven Design, DDD). Этот подход позволяет четко выделить выделить домены со своей моделью данных.  

== Основные шаги:
. Анализ существующего монолита и его функциональности.
. Выделение доменных(субдоменных) областей.
. Выделение границ микросервисов для обеспечения независимости друг от друга.
.  Настройка связей между модулями системы.
. Миграция функциональности из монолита в микросервисы.

== Доменные области бизнеса
. Управление товарами: включает в себя управление каталогом товаров, их характеристиками, ценами и наличием на складах.
. Управление заказами: отвечает за проверку наличия товаров, создание, обработку и выполнение заказов клиентов.
. Управление клиентами: включает в себя регистрацию клиентов, управление их профилями и историей заказов.
. Управление складами: включает в себя управление товарами на собственых складах и проверку наличия товаров на складах поставщиков. 
. Управление доставкой: включает в себя планирование и выполнение доставки товаров клиентам.
. Управление платежами: отвечает за обработку платежей и другие транзакции.

== Выделенные микросервисы
. *Product Service*: управление товарами и их характеристиками.
. *Order Service*: управление заказами и их статусами.
. *Customer Service*: управление клиентами и их данными.
. *Inventory Service*: проверка товаров на наличие на складах.
. *Delivery Service*: управление процессом доставки.
. *Payment Service*: обработка платежей и возвратов

== Заключение
Переход от монолита к микросервисам позволяет улучшить масштабируемость, гибкость, обеспечить непрерывное развертывание, высокую надежность, а также упростить процесс разработки и тестирования. 

== Контекстная диаграмма
image: /Users/dunice/Documents/Solodovnik_analytics_practice/out/Контекстная диаграмма/Контекстная диаграмма.svg[]
