@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for Shop

Person(customer, "Пользователь", "Просматривает каталог компании товаров, совершает различные операции в системе")
Person(administrator, "Оператор", "Проверяет работоспособность систем, поддерживает функциональность")
System(General_system, "Система управления маркетинговыми процессами", "Продажа товаров, проверка наличия на складах, организация доставки и управление платежами")
System_Ext(Payment_system, "Система обработки платажей", "Совершение покупок, управление транзакциями.")
Rel(customer, General_system, "Использует")
Rel(administrator, General_system, "Вносит правки при необходимости")
Rel(General_system, Payment_system, "Взаимодействует с")

@enduml

